Iter13
chemax/url-shorter pull request #13
Opened 2023-10-15 06:45 UTC by chemax

2023-10-21 13:50 UTC, popoffvg requested changes

2023-10-21 13:50 UTC, popoffvg commented on mockgen.sh
> +mockgen -source=./util/util.go -destination=./mocks/storage/storage_mock.go StorageInterface
[minor] 
В go принято использовать makefile для автоматизации работы. 
Если все же нужны скрипты, то лучше не хранить их в корне проекта. 
См. https://github.com/golang-standards/project-layout, https://go.dev/doc/modules/layout

2023-10-21 13:50 UTC, popoffvg commented on internal/app/app.go
>  	err = http.ListenAndServe(cfg.GetNetAddr(), handler.Router)
[minor]

Стоит всегда проверять errors.Is(err, http.ErrServerClosed), т.к. ошибка возвращается всегда при вызове shutdown

2023-10-21 13:50 UTC, popoffvg commented on internal/db/db.go
> +func (db *DB) createURLsTable() error {
[minor]

Лучше использовать миграции. Это позволяет версионировать схемы и решает проблемы с откатами версий схемы в случае нарушений обратной совместимости при релизах. 
https://github.com/pressly/goose
https://github.com/pressly/goose

2023-10-21 13:50 UTC, popoffvg commented on internal/db/db.go
> +	ctx        context.Context
[major]

Не стоит хранить контекст в структуре отвечающий за БД, тем более ты его не завершаешь никогда (сейчас это context.Background). 
Дополнительно, у возникнут проблемы с gracefull shutdown, т.к. контекст будет завершен сразу же при получении сигнала ОС и возможно будет закрыто соединение с БД. А оно должно оставаться открытым до выполнения всех запросов.

Контекст обычно request-scope переменная. 
У Gracefull shutdown обычно делают свой контекст с тайм-аутом. Поэтому если есть фоновые задания, которые нужно завершить, то лучше возвращать cancel-функцию 
```
type cancel func() error
InitDB(cfg config.DB) (cancel, error)
```

2023-10-21 13:50 UTC, popoffvg commented on internal/db/db.go
> +	select * from new
[minor]

Лучше не использовать * в запросах, т.к. большинство библиотек кидают ошибку при несовпадении полей запроса и структуры. Закатка миграции без переделок сервиса может привести к его неработоспособности.

2023-10-21 13:50 UTC, popoffvg commented on internal/db/db.go
> +  URL text unique not null
[minor]

Стоит добавить индексы по условиям запросов

2023-10-21 13:50 UTC, popoffvg commented on internal/db/db.go
> +	conn       *pgx.Conn
[major]

Стоит использовать pgxpool, а не одно соединение. Сейчас сервер может обрабатывать только один запрос ||.

2023-10-21 13:50 UTC, popoffvg commented on internal/handlers/post.go
> +		if errors.Is(err, &util.AlreadyHaveThisURLError{}) {
[major]

Не стоит писать при обработке ошибок `if else`, т.к. это приводит к ошибкам. 

Стоит использовать ранний return
```go
if err != nil{
    if errors.Is(err, &util.AlreadyHaveThisURLError{}) {
        handlerError(w,  err) // определяем код возврата по типу ошибки для всех хендлеров одинаково
        return
    }
}
```

2023-10-21 13:50 UTC, popoffvg commented on internal/storage/storage.go
> +		//TODO переделать на функции внутри postgresql?
retry защищает от сетевых проблем с БД. 
Переход на процедуры внутри БД проблемы с сетью не решит

2023-10-21 13:50 UTC, popoffvg commented on util/util.go
> +type AlreadyHaveThisURLError struct {
[minor]

Тут лучше не делать тип, а объявить переменную:
var AlreadyHaveThisURLError = errors.New("already have this url in db")

Типы используются когда нужно кастомизировать поведение ошибки и обычно для них реализуют возможность враппинга ошибок (см.Unwrap https://pkg.go.dev/errors#Unwrap), что сложно

2023-10-21 13:50 UTC, popoffvg commented on util/util.go
> +	Use() bool
[major]

Метод Use не относится к БД и лучше под него выделить отдельный интерфейс

2023-10-21 13:50 UTC, popoffvg commented on util/util.go
> +type AlreadyHaveThisURLError struct {
[minor]

Лучше избегать пакета util, т.к. он быстро превращается в свалку всего в реальном проекте.

Интерфейс следует объявлять рядом с местом использования или в отдельном пакете.

Ошибки стоит размешать рядом с бизнес-логикой или в отдельном пакете.

2023-10-22 09:39 UTC, chemax commented on internal/db/db.go
> +func (db *DB) createURLsTable() error {
> [minor]
> 
> Лучше использовать миграции. Это позволяет версионировать схемы и решает проблемы с откатами версий схемы в случае нарушений обратной совместимости при релизах. https://github.com/golang-standards/project-layout https://github.com/pressly/goose

Я так предположил, что миграции должны быть позже, я, собственно, планировал их использовать, но по заданию приложение должно создавать таблицу при старте, а миграции, как я считаю, должны запускаться "снаружи". Встраивать их мне не нравится.

2023-10-24 03:17 UTC, chemax commented on internal/storage/storage.go
> +		//TODO переделать на функции внутри postgresql?
Я тут про генерацию shortcode внутри самой БД, не про сетевые проблемы.

2023-10-24 03:23 UTC, chemax commented on util/util.go
> +type AlreadyHaveThisURLError struct {
Интерфейсы вынес, буду стараться не захламлять его.

2023-10-24 18:35 UTC, popoffvg commented on internal/db/db.go
> +func (db *DB) createURLsTable() error {
Миграций дальше не будет. Вариантов как с ними поступить 2:
- накатывать любым инструментов снаружи (тесты к такому не готовы)
- встраивать

И тот, и тот вариант встречаются в реальности, хотя бы на тестовых стендах. Поэтому на стандартные библиотеки в экосистеме go стоит обратить внимание.

2023-10-24 18:44 UTC, popoffvg approved these changes
Не стал исправлять на pool. Буду считать, что сделал это осозанно =) 
На всякий случай оставлю статью про взаимодейтсвия приложения на go и PostgreSQL:
- https://habr.com/ru/companies/avito/articles/716516/

2023-10-25 02:42 UTC, merged