Iter18
chemax/url-shorter pull request #18
Opened 2024-01-30 06:16 UTC by chemax

2024-02-02 01:26 UTC, capsulated requested changes
Бенчмарки - ок
Документация - 50/50, так как internal документацией не покрывается
goimports - ок

Необходимо пофиксить следующее:
1. Очень много моков. Для каждого пакета делать моки не имеет смысла. В частности, для конфига - точно не нужен мок. Мок полезен, скажем, в стороннем API или для базы данных. Для абсолютно всех объектов делать мок - это перебор (исправлять по желанию, так как это с предыдущих спринтов от предыдущего ментора).
2. Нейминг структур. Слово struct в нейминге необходимо убрать - имя переменной не должно демонстрировать реализацию
3. Очень много `todo`. Так как инкременты максимально приближены к реальной разработке, будем придерживаться этих правил. В enterprise проектах, в большинстве случаев, в master/main ветку todo комментарии не попадают, только в промежуточных коммитах
4. Почти вся логика приложения в `internal`. Необходимо выделить пакеты, которые могут быть использованы в других приложениях go и перенести их в pkg. Яркий пример - это gzip компресcор. Также, часть функционал авторизации можно перенести в независимый пакет, который можно переиспользовать. Глянь, какой из функционала у тебя дублируется в gofermart. Этот функционал смело можно выделять в независимые пакеты и переносить в pkg. Причём, во втором выпускном можно импортировать эти пакеты из текущего - яркий пример переиспользования кода

2024-02-02 02:56 UTC, chemax commented on internal/users/users.go
> +type usersStruct struct {
Затем, что шарить эту структуру из пакета не нужно, а я по запаре пошарил. А как её назвать мне фантазии не хватает. Это чисто внутренняя штука для этого пакета, наружу она отдаётся через init. Как мне в этой ситуации её называть - не представляю.

2024-02-02 02:57 UTC, chemax commented on internal/users/users.go
> +type usersStruct struct {
Так же и с остальным, я просто убирал экспорт

2024-02-09 02:10 UTC, capsulated approved these changes
По текущему спринту всё ок.

Есть ещё замечание по интерфейсам. Скажем, интерфейс для config в данной работе не особо нужен. В разделе по антипаттернам есть немного об этом, что не нужно добавлять интерфейсы везде: лучше только там, где они необходимы. Хотя программировать на основе интерфейсов - это отличная практика, что мы также обсуждали на 1-1). Но лучше в следующем спринте интерфейсы оставить только там, где они необходимы

2024-02-09 02:52 UTC, merged